from textdistance import levenshtein

niz2 = '''<tr>
   <td>
    <table>
     <tbody>
      <tr>
       <td>
        <a>
         More Info...
        </a>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
   <td>
    <a>
     <b>
      #text
     </b>
    </a>
    <table>
     <tbody>
      <tr>
       <td>
        <table>
         <tbody>
          <tr>
           <td>
            <b>
             List Price:
            </b>
           </td>
           <td>
            <s>
             #text
            </s>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             Price:
            </b>
           </td>
           <td>
            <span>
             <b>
              #text
             </b>
            </span>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             You Save:
            </b>
           </td>
           <td>
            <span>
             #text
            </span>
           </td>
          </tr>
         </tbody>
        </table>
       </td>
       <td>
        <span>
         #text
         <a>
          <span>
           <b>
            Click here to purchase.
           </b>
          </span>
         </a>
        </span>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
  </tr>'''

niz1 = '''<tr>
   <td>
    <table>
     <tbody>
      <tr>
       <td>
        <a>
         More Info...
        </a>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
   <td>
    <a>
     <b>
      #text
     </b>
    </a>
    <table>
     <tbody>
      <tr>
       <td>
        <table>
         <tbody>
          <tr>
           <td>
            <b>
             List Price:
            </b>
           </td>
           <td>
            <s>
             #text
            </s>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             Price:
            </b>
           </td>
           <td>
            <span>
             <b>
              #text
             </b>
            </span>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             You Save:
            </b>
           </td>
           <td>
            <span>
             #text
            </span>
           </td>
          </tr>
         </tbody>
        </table>
       </td>
       <td>
        <span>
         #text
         <a>
          <span>
           <b>
            Click here to purchase.
           </b>
          </span>
         </a>
        </span>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
  </tr>'''

niz3 = '''<tr>
   <td>
    <table>
     <tbody>
      <tr>
       <td>
        <a>
         More Info...
        </a>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
   <td>
    <a>
     <b>
      #text
     </b>
    </a>
    <table>
     <tbody>
      <tr>
       <td>
        <table>
         <tbody>
          <tr>
           <td>
            <b>
             List Price:
            </b>
           </td>
           <td>
            <s>
             #text
            </s>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             Price:
            </b>
           </td>
           <td>
            <span>
             <b>
              #text
             </b>
            </span>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             You Save:
            </b>
           </td>
           <td>
            <span>
             #text
            </span>
           </td>
          </tr>
         </tbody>
        </table>
       </td>
       <td>
        <span>
         #text
         <a>
          <span>
           <b>
            Click here to purchase.
           </b>
          </span>
         </a>
        </span>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
  </tr>'''

niz4 = '''<tr>
   <td>
    <table>
     <tbody>
      <tr>
       <td>
        <a>
         More Info...
        </a>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
   <td>
    <a>
     <b>
      #text
     </b>
    </a>
    <table>
     <tbody>
      <tr>
       <td>
        <table>
         <tbody>
          <tr>
           <td>
            <b>
             List Price:
            </b>
           </td>
           <td>
            <s>
             #text
            </s>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             Price:
            </b>
           </td>
           <td>
            <span>
             <b>
              #text
             </b>
            </span>
           </td>
          </tr>
          <tr>
           <td>
            <b>
             You Save:
            </b>
           </td>
           <td>
            <span>
             #text
            </span>
           </td>
          </tr>
         </tbody>
        </table>
       </td>
       <td>
        <span>
         #text
         <a>
          <span>
           <b>
            Click here to purchase.
           </b>
          </span>
         </a>
        </span>
       </td>
      </tr>
     </tbody>
    </table>
   </td>
  </tr>'''

print(levenshtein.distance(niz3, niz4))